"""empty message

Revision ID: e082893823fd
Revises: 35683990a9f2
Create Date: 2020-01-25 14:49:51.131665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e082893823fd'
down_revision = '35683990a9f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('address', table_name='person')
    op.drop_index('full_name', table_name='person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('full_name', 'person', ['full_name'], unique=True)
    op.create_index('address', 'person', ['address'], unique=True)
    # ### end Alembic commands ###
